INFO 2021-06-08 11:10:41,982 remote_connection.py:117 __init__ Could not connect to port 4723 on host localhost
INFO 2021-06-08 11:10:41,983 remote_connection.py:136 __init__ Could not get IP address for host: localhost
DEBUG 2021-06-08 11:10:41,985 remote_connection.py:388 _request POST http://localhost:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:platformVersion": "11", "appium:deviceName": "89LJQWROR47TCYKJ", "appium:appPackage": "com.xunmeng.pinduoduo", "appium:appActivity": ".ui.activity.MainFrameActivity", "appium:unicodeKeyboard": false, "appium:resetKeyboard": false, "appium:noReset": true, "appium:newCommandTimeout": 6000, "appium:automationName": "UiAutomator2"}]}, "desiredCapabilities": {"platformName": "Android", "platformVersion": "11", "deviceName": "89LJQWROR47TCYKJ", "appPackage": "com.xunmeng.pinduoduo", "appActivity": ".ui.activity.MainFrameActivity", "unicodeKeyboard": false, "resetKeyboard": false, "noReset": true, "newCommandTimeout": 6000, "automationName": "UiAutomator2"}}
DEBUG 2021-06-08 11:10:41,986 connectionpool.py:231 _new_conn Starting new HTTP connection (1): localhost:4723
